# Generated by Django 3.0.3 on 2020-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('sensor', models.IntegerField(default=0)),
                ('datetime', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('humidity', models.FileField(upload_to='')),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
            ],
        ),
    ]
