# Generated by Django 3.0.3 on 2020-02-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0002_auto_20200228_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reading',
            new_name='SENSORS',
        ),
    ]
