# Generated by Django 3.0.3 on 2020-02-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0003_auto_20200228_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SENSORS',
            new_name='Readings',
        ),
    ]
